### ISSUE TITLE
Feature request: differentiate between links and images in validation reports

### ISSUE THREAD

**Issue by joelnitta** [carpentries/pegboard#143]
When lesson validation runs (via `build_lesson()`), I get a message about broken links, but no indication of the actual URL, so it is difficult to act on this information.

```
── Validating Internal Links and Images 
! There were errors in 3/80 links
```

`sandpaper v 0.14.1`

**Comment by joelnitta** [comment]
Hm... I just updated to the most recent `pegboard` (0.7.1) and `sandpaper` (0.14.1), and I'm still not seeing the URLs of the reported links:

```
> build_lesson(rebuild=TRUE)
── Validating Fenced Divs ────────────────────────────────────────────
── Validating Internal Links and Images ──────────────────────────────
! There were errors in 3/80 links
◌ Images need alt-text <https://webaim.org/techniques/hypertext/link_text#alt_link>

episodes/introduction.Rmd:87 [image missing alt-text]: https://allisonhorst.github.io/palmerpenguins/reference/figures/lter_penguins.png
episodes/basic-targets.Rmd:170 [image missing alt-text]: https://allisonhorst.github.io/palmerpenguins/reference/figures/culmen_depth.png
episodes/quarto.Rmd:73 [image missing alt-text]: https://ucsbcarpentry.github.io/Reproducible-Publications-with-RStudio-Quarto/fig/03-qmd-workflow.png
ℹ Consent to use package cache provided
```

Furthermore, the images that have been reported as missing alt-text actually do have alt-text, but I think that should be a separate issue.

FYI the lesson I am trying to build is here: https://github.com/carpentries-incubator/targets-workshop

**Comment by joelnitta** [comment]
> do you think it would be helpful to populate the source marker pane in RStudio (akin to the way {lintr} displays errors)?

Sure, although I think if the checks were reported correctly during `build_lesson()`, that would probably be sufficient.

**Comment by zkamvar** [comment]
Ah! I think I see what the problem is! It's none other than our old friend, fluid representations!

In terms of {pegboard}, it processes images and links the same way because an image is a special class of link, and I never ended up writing text to distinguish them -_-

For the breadcrumbs, when you call `sandpaper::validate_lesson()`, it will call the `$validate_links()` method for each Markdown file, which is stored as an `Episode` object:

https://github.com/carpentries/pegboard/blob/e7e5c4555e13a09bf9f53ec903dc9c0a462ed789/R/Episode.R#L629-L635

This will call the (poorly documented) `throw_link_warnings()` function, which will collect the information from the validation table and present it in a friendly fashion, passing it to the `issue_warnings()` function:

https://github.com/carpentries/pegboard/blob/e7e5c4555e13a09bf9f53ec903dc9c0a462ed789/R/utils-validation.R#L58-L63

`issue_warnings()` generates the summary that you see printed:

https://github.com/carpentries/pegboard/blob/e7e5c4555e13a09bf9f53ec903dc9c0a462ed789/R/utils-cli.R#L36-L39

What I could do is to modify the `throw_link_warnings()` function to switch between "links", "images", and "links and images" depending on the errors so that it's more clear.

**Comment by zkamvar** [comment]
In terms of the alt text reporting, the reports are correct.

The markdown syntax for The Workbench comes from pandoc, which uses the square braces for captions, not alt text (see https://carpentries.github.io/sandpaper-docs/style.html#figures).

I would suggest something like this: 

```markdown
![The three species of penguins in the `palmerpenguins` dataset. Artwork by @allison_horst.
](https://allisonhorst.github.io/palmerpenguins/reference/figures/lter_penguins.png){
alt="Illustration of three penguins with colourful backgrounds.
Labels above their heads read: 'Chinstrap!', 'Gentoo!', and 'Adélie'"
}
```
